# Comprehensive Render Blueprint for Dr. Fintan Medical Appointment System
# This file defines the complete infrastructure and deployment configuration

services:
  # Main Web Application
  - type: web
    name: dr-fintan-medical-app
    env: php
    plan: starter
    buildCommand: |
      # Install PHP dependencies
      composer install --no-dev --optimize-autoloader
      
      # Install Node.js dependencies
      npm ci
      
      # Build frontend assets
      npm run build
      
      # Generate application key if not set
      php artisan key:generate --force
      
      # Publish vendor assets
      php artisan vendor:publish --provider="Spatie\MediaLibrary\MediaLibraryServiceProvider" --tag="medialibrary-migrations" --force
      php artisan vendor:publish --provider="Spatie\Tags\TagsServiceProvider" --tag="tags-migrations" --force
      
      # Clear and cache configuration
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      
      # Create storage link
      php artisan storage:link
      
      # Set proper permissions
      chmod -R 775 storage bootstrap/cache
      
      # Create required directories
      mkdir -p storage/app/public/uploads
      mkdir -p storage/logs
      mkdir -p bootstrap/cache
    startCommand: |
      # Run database migrations
      php artisan migrate --force
      
      # Seed essential data
      php artisan db:seed --class=SiteSettingsSeeder --force
      php artisan db:seed --class=HomePageContentSeeder --force
      php artisan db:seed --class=AboutPageContentSeeder --force
      php artisan db:seed --class=ContactPageContentSeeder --force
      php artisan db:seed --class=UserSeeder --force
      php artisan db:seed --class=DoctorSeeder --force
      php artisan db:seed --class=DoctorScheduleSeeder --force
      
      # Start the web server
      php artisan serve --host=0.0.0.0 --port=$PORT
    healthCheckPath: /health-check
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: dr-fintan-medical-app
          property: host
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: public
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: dr-fintan-mysql
          property: host
      - key: DB_PORT
        fromDatabase:
          name: dr-fintan-mysql
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: dr-fintan-mysql
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: dr-fintan-mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: dr-fintan-mysql
          property: password
      # API Keys (set these in Render dashboard)
      - key: NOTIFICATION_API_CLIENT_ID
        sync: false
      - key: NOTIFICATION_API_CLIENT_SECRET
        sync: false
      - key: DAILY_API_KEY
        sync: false
      - key: DAILY_DOMAIN
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      # Mail Configuration
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: "Dr. Fintan Medical Platform"
      # Push Notifications
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      # Security
      - key: BCRYPT_ROUNDS
        value: 12
      - key: SANCTUM_STATEFUL_DOMAINS
        fromService:
          type: web
          name: dr-fintan-medical-app
          property: host

  # Background Queue Worker
  - type: worker
    name: dr-fintan-queue-worker
    env: php
    plan: starter
    buildCommand: |
      composer install --no-dev --optimize-autoloader
    startCommand: |
      # Start queue worker with proper configuration
      php artisan queue:work database --sleep=3 --tries=3 --max-time=3600 --timeout=60 --daemon
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: QUEUE_CONNECTION
        value: database
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: dr-fintan-mysql
          property: host
      - key: DB_PORT
        fromDatabase:
          name: dr-fintan-mysql
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: dr-fintan-mysql
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: dr-fintan-mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: dr-fintan-mysql
          property: password
      - key: NOTIFICATION_API_CLIENT_ID
        sync: false
      - key: NOTIFICATION_API_CLIENT_SECRET
        sync: false

  # Laravel Scheduler (runs every minute)
  - type: cron
    name: dr-fintan-scheduler
    env: php
    plan: starter
    schedule: "* * * * *"  # Every minute
    buildCommand: |
      composer install --no-dev --optimize-autoloader
    startCommand: |
      php artisan schedule:run
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: dr-fintan-mysql
          property: host
      - key: DB_PORT
        fromDatabase:
          name: dr-fintan-mysql
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: dr-fintan-mysql
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: dr-fintan-mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: dr-fintan-mysql
          property: password

  # Appointment Reminder Service
  - type: cron
    name: appointment-reminders
    env: php
    plan: starter
    schedule: "0 */2 * * *"  # Every 2 hours
    buildCommand: |
      composer install --no-dev --optimize-autoloader
    startCommand: |
      php artisan appointments:schedule-reminders
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: dr-fintan-mysql
          property: host
      - key: DB_PORT
        fromDatabase:
          name: dr-fintan-mysql
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: dr-fintan-mysql
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: dr-fintan-mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: dr-fintan-mysql
          property: password
      - key: NOTIFICATION_API_CLIENT_ID
        sync: false
      - key: NOTIFICATION_API_CLIENT_SECRET
        sync: false
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: "Dr. Fintan Medical Platform"

  # Daily Cleanup Tasks
  - type: cron
    name: daily-cleanup
    env: php
    plan: starter
    schedule: "0 2 * * *"  # Daily at 2 AM UTC
    buildCommand: |
      composer install --no-dev --optimize-autoloader
    startCommand: |
      # Clean up expired rooms and failed jobs
      php artisan cleanup:expired-rooms
      php artisan queue:prune-failed --hours=48
      php artisan queue:flush
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: dr-fintan-mysql
          property: host
      - key: DB_PORT
        fromDatabase:
          name: dr-fintan-mysql
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: dr-fintan-mysql
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: dr-fintan-mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: dr-fintan-mysql
          property: password
      - key: DAILY_API_KEY
        sync: false
      - key: QUEUE_CONNECTION
        value: database

  # Weekly Maintenance Tasks
  - type: cron
    name: weekly-maintenance
    env: php
    plan: starter
    schedule: "0 3 * * 0"  # Weekly on Sunday at 3 AM UTC
    buildCommand: |
      composer install --no-dev --optimize-autoloader
    startCommand: |
      # Clear and rebuild caches
      php artisan optimize:clear
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      # Clean up old log files
      find storage/logs -name "*.log" -mtime +30 -delete
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: dr-fintan-mysql
          property: host
      - key: DB_PORT
        fromDatabase:
          name: dr-fintan-mysql
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: dr-fintan-mysql
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: dr-fintan-mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: dr-fintan-mysql
          property: password

  # Database Backup Service
  - type: cron
    name: database-backup
    env: php
    plan: starter
    schedule: "0 1 * * *"  # Daily at 1 AM UTC
    buildCommand: |
      composer install --no-dev --optimize-autoloader
    startCommand: |
      # Create database backup
      php artisan backup:run --only-db
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: dr-fintan-mysql
          property: host
      - key: DB_PORT
        fromDatabase:
          name: dr-fintan-mysql
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: dr-fintan-mysql
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: dr-fintan-mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: dr-fintan-mysql
          property: password

# Database Configuration
databases:
  - name: dr-fintan-mysql
    databaseName: dr_fintan_db
    user: dr_fintan_user
    plan: starter


