# Comprehensive Render Blueprint for Dr. Fintan Medical Appointment System
# This file defines the complete infrastructure and deployment configuration using Docker

services:
  # Main Web Application with Docker
  - type: web
    name: dr-fintan-medical-app
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: dr-fintan-medical-app
          property: host
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: public
      # Database Configuration - Set these in Render Dashboard
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      # API Keys (set these in Render dashboard)
      - key: NOTIFICATION_API_CLIENT_ID
        sync: false
      - key: NOTIFICATION_API_CLIENT_SECRET
        sync: false
      - key: DAILY_API_KEY
        sync: false
      - key: DAILY_DOMAIN
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      # Mail Configuration
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: "Dr. Fintan Medical Platform"
      # Push Notifications
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      # Security
      - key: BCRYPT_ROUNDS
        value: 12
      - key: SANCTUM_STATEFUL_DOMAINS
        fromService:
          type: web
          name: dr-fintan-medical-app
          property: host

  # Note: Queue workers, cron jobs, and background tasks are now handled 
  # within the main Docker container using supervisor and cron

# Database Configuration
# Using remote database - no local database service needed


